# Generated by Django 2.2.6 on 2019-10-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('registered_on', models.DateField()),
                ('account_type', models.CharField(choices=[('R', 'Regular'), ('G', 'Gold'), ('P', 'Platinum')], default='R', max_length=1)),
            ],
        ),
    ]
